Reusable workflows do not work with environments

diff --git a/.github/workflows/pumps-staging.yml b/.github/workflows/pumps-staging.yml
--- a/.github/workflows/pumps-staging.yml
+++ b/.github/workflows/pumps-staging.yml
@@ -7,11 +7,47 @@ on:
     - cron: '0 4 * * 0'
 
 jobs:
-  pumps-staging:
-    runs-on: ubuntu-latest
+  collect_pumps:
     environment: staging
-    uses: ./.github/workflows/pumps.yml
-    with:
-      SUPABASE_URL: ${{ vars.SUPABASE_URL }}
-      SUPABASE_DATA_ASSETS_BUCKET: ${{ vars.SUPABASE_DATA_ASSETS_BUCKET }}
-      SUPABASE_ACCESS_TOKEN: ${{ vars.SUPABASE_ACCESS_TOKEN }}
+    runs-on: ubuntu-latest
+    name: A job to aggregate pumps data from open street maps and push to GDK Supabase
+    steps:
+      - name: Pumps data generate step
+        uses: ./ # Uses an action in the root directory
+        id: pumps
+        with:
+          outfile-path: "out/pumps.geojson"
+      - name: File output
+        run: echo "The file was written to ${{ steps.pumps.outputs.file }}"
+      - name: Upload file to supabase
+        run: |
+          getStatusCode=$(curl -s -o /dev/null -w "%{http_code}" \
+            -X GET \
+            ${{ inputs.SUPABASE_URL }}/storage/v1/object/info/public/${{ inputs.SUPABASE_DATA_ASSETS_BUCKET }}/pumps.geojson)
+          if [ "$getStatusCode" = "200" ]; then
+            putStatusCode=$(curl -s -o /dev/null -w "%{http_code}" \
+              -X PUT \
+              -H "Authorization: Bearer ${{ secrets.SUPABASE_ACCESS_TOKEN }}" \
+              -H "Content-Type: application/geo+json" \
+              -d "@${{ steps.pumps.outputs.file }}" \
+              ${{ inputs.SUPABASE_URL }}/storage/v1/object/${{ inputs.SUPABASE_DATA_ASSETS_BUCKET }}/pumps.geojson)
+            if [ "$putStatusCode" = "200" ]; then
+              echo "Uploading to Supabase successful"
+            else
+              echo "Uploading to Supabase failed"
+              exit 1
+            fi
+          else
+            postStatusCode=$(curl -s -o /dev/null -w "%{http_code}" \
+              -X POST \
+              -H "Authorization: Bearer ${{ secrets.SUPABASE_ACCESS_TOKEN }}" \
+              -H "Content-Type: application/geo+json" \
+              -d "@${{ steps.pumps.outputs.file }}" \
+              ${{ inputs.SUPABASE_URL }}/storage/v1/object/${{ inputs.SUPABASE_DATA_ASSETS_BUCKET }}/pumps.geojson)
+            if [ "$postStatusCode" = "200" ]; then
+              echo "Uploading to Supabase successful"
+            else
+              echo "Uploading to Supabase failed"
+              exit 1
+            fi
+          fi
